#!/bin/bash -efux
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2023  Alexey Gladkov <gladkov.alexey@gmail.com>

testcase="$1"; shift

curdir="$(readlink -ev "$0")"
curdir="${curdir%/*}"
topdir="${curdir%/*}"

readonly builddir=/srv
readonly IMAGE=alt:sisyphus

echo 0 > /proc/sys/fs/protected_hardlinks

git clone -b hasher-in-podman-v1 https://github.com/legionus/hasher-priv

mkdir -v -p -- "$curdir/tmp"
cat > "$curdir/tmp/run.sh" <<-EOF
#!/bin/bash -eux

apt-get -y -qq update

: hasher-priv requires
apt-get -y -qq install \
	help2man setproctitle-devel gcc make glibc-utils

: mkimage requires
apt-get -y -qq install \
	libshell hasher make shellcheck \
	cpio diffutils findutils tar squashfs-tools bsdtar file sed

cd "$builddir"

cd hasher-priv/hasher-priv
	make install
cd -

id

hasher-useradd -f "\$(id -u -n)"
mkdir -p -- \$HOME/hasher

: "Prepare services"
tee /etc/syslog.conf <<EOF1
*.* -/var/log/syslog/messages
EOF1

tee /etc/hasher-priv/system <<EOF1
prefix=~:/tmp/.private:$builddir
allowed_mountpoints=/proc,/dev/pts,/dev
min_uid=-1
min_gid=-1
EOF1

hasher-privd -l debug >/tmp/hasher-privd.log 2>&1 &

: "Build"
make

: "Tests"
rc=0
make check TESTS="$testcase" || rc=\$?

cat tests/*.log ||:
cat /tmp/hasher-privd.log ||:

exit \$rc
EOF

chmod +x -- "$curdir/tmp/run.sh"

podman run --privileged --systemd=false --rm --tty --interactive \
	--volume="$topdir:$builddir" \
	"$IMAGE" "$builddir/tests/tmp/run.sh"
