#!/bin/sh -efu

mkdir -p -- /usr/share/alt-notes

cat >/usr/share/alt-notes/release-notes.ru.html <<EOF
<html>
<head>
    <meta http-equiv="content-type" value="text/html;charset=utf-8"/>
</head>
<body>
    <p>Дистрибутив ALT Linux Server установлен.</p>
    <p>Протоколы установки находятся в каталоге <em>/root/.install-log/</em></p>
</body>
</html>
EOF

cat >/usr/share/alt-notes/release-notes.all.html <<EOF
<html>
<head>
    <meta http-equiv="content-type" value="text/html;charset=utf-8"/>
</head>
<body>
    <p>ALT Linux Server distribution is installed and ready to use.</p>
    <p>Log files from installation process are in <em>/root/.install-log/</em> directory</p>
</body>
</html>
EOF

cat >/usr/share/alt-notes/license.all.html <<EOF
<html>
<head>
    <title>Notification: terms of use of the Software and the Works Contained therein</title>
    <meta http-equiv="content-type" value="text/html;charset=utf-8"/>
</head>
<body>
    <h1>Notification: terms of use of the Software and the Works Contained therein</h1>
    <p>Do whatever you want.</p>
</body>
</html>
EOF

cat >/usr/share/alt-notes/license.ru.html <<EOF
<html>
<head>
    <title>Уведомление о правах</title>
    <meta http-equiv="content-type" value="text/html;charset=utf-8"/>
</head>
<body>
    <h1>Уведомление о правах</h1>
    <p>Делайте, что хотите.</p>
</body>
</html>
EOF
