#!/bin/sh

bootlogo="/usr/share/gfxboot/$INFO_THEME/bootlogo"

if [ ! -f "$bootlogo" ]; then
	echo "${0##*/} - SKIP"
	exit 0
fi
mkdir -p "$WORKDIR"/isolinux
cd "$WORKDIR"/isolinux 

cp -a "$bootlogo" bootlogo.cpio

cpio -Vuid < bootlogo.cpio
rm -f bootlogo.cpio

printf "init\nlanguages\n" |
	cpio -Vo > ./bootlogo
