#!/bin/ash -efu

. shell-error

verbose="${VERBOSE:+-v}"
quiet="${QUIET:+-q}"

dir="${WORKDIR:?workdir required}"
verbose "Work directory: $dir"

hshcmd="hsh-run '$dir' --rooter --pty --mount=/dev/pts $verbose $quiet ${NUMBER:+--number="$NUMBER"}"

case "$PROG" in
	*-run)  exec env -i PATH="$PATH" $hshcmd "$@" ;;
	*-exec) exec env -i PATH="$PATH" $hshcmd --execute="$1" ;;
esac
