#!/bin/ash -efu

. shell-error

verbose="${VERBOSE:+-v}"
quiet="${QUIET:+-q}"

dir="${WORKDIR:?workdir required}"
verbose "Work directory: $dir"

case "$PROG" in
	*-run)
		exec env -i PATH="$PATH" \
		hsh-run --rooter $verbose $quiet ${HSH_NUMBER:+--number="$HSH_NUMBER"} "$dir" "$@"
		;;
	*-exec)
		exec env -i PATH="$PATH" \
		hsh-run --rooter $verbose $quiet ${HSH_NUMBER:+--number="$HSH_NUMBER"} "$dir" --execute="$1"
		;;
esac
