#!/bin/ash -efu

. shell-error

verbose="${VERBOSE:+-v}"
quiet="${QUIET:+-q}"
data_tree="${MKI_DATA_TREE:?Data required}"
dir="${WORKDIR:?work directory required}"

[ -d "$data_tree" ] ||
	exit 0

chroot="$dir/chroot"
[ -d "$chroot" ] ||
	exit 0

cp_args=
dev_number1="$(stat -c '%d' "$data_tree")"
dev_number2="$(stat -c '%d' "$chroot")"

[ "$dev_number1" -ne "$dev_number2" ] ||
	cp_args='-l'

find "$data_tree" -mindepth 1 -maxdepth 1 |xargs -r cp $cp_args -at "$chroot/.in/" --

cat > "$chroot/tmp/script" <<EOF
#!/bin/sh -efu
/.host/find /.in -mindepth 1 -maxdepth 1 |xargs -r cp $verbose -alt /.subworkdir --
EOF
chroot-exec "$chroot/tmp/script"
rm -f -- "$chroot/tmp/script"

find "$chroot/.in/" -mindepth 1 -maxdepth 1 |xargs -r rm -rf --
