#!/bin/ash -efu

. shell-error

dir="${WORKDIR:?workdir required}"

case "$PROG" in
	*-image-*) dir="$dir/chroot/.subworkdir" ;;
esac

[ -d "$dir/chroot" ] ||
	show_usage "$dir: Directory not look like hasher workdir"

verbose "Work directory: $dir"

hasher_args="${VERBOSE:+-v} ${QUIET:+-q} ${HSH_EXCLUDE_DOCS:+--excludedocs} ${HSH_NUMBER:+--number="$HSH_NUMBER"}"
REQUIRES="$@"

if [ -f "$REQUIRES" ]; then
	grep -v '^[[:space:]]*#' "$REQUIRES" |
		xargs -r \
			env -i PATH="$PATH" hsh-install $hasher_args -- "$dir"
else
	env -i PATH="$PATH" hsh-install $hasher_args -- "$dir" $REQUIRES
fi
