#!/bin/ash -efu

. shell-error

dir="${WORKDIR:?workdir required}"
subdir="$dir/.subworkdir"

verbose "Work directory: $dir"

hasher_args="--clean ${VERBOSE:+-v} ${QUIET:+-q} ${NUMBER:+--number="$NUMBER"}"

if [ -d "$subdir/chroot" ]; then
	env -i PATH="$PATH" hsh $hasher_args "$subdir" ||
		fatal "$subdir: Unable to clean workdir: rc=$?"
fi

if [ -d "$dir/chroot" ]; then
	env -i PATH="$PATH" hsh $hasher_args "$dir" ||
		fatal "$dir: Unable to clean workdir: rc=$?"
fi
