#!/bin/ash -efu

. shell-error

dir="${WORKDIR:?workdir required}"
[ -d "$dir/chroot" ] ||
	show_usage "$dir: Directory not look like hasher workdir"

verbose "Work directory: $dir"

hasher_args="${VERBOSE:+-v} ${QUIET:+-q} ${EXCLUDE_DOCS:+--excludedocs} ${NUMBER:+--number="$NUMBER"}"
REQUIRES="${REQUIRES:-}"

if [ -f "$REQUIRES" ]; then
	grep -v '^[[:space:]]*#' "$REQUIRES" |
		xargs -r \
			env -i PATH="$PATH" hsh-install $hasher_args -- "$dir"
else
	env -i PATH="$PATH" hsh-install $hasher_args -- "$dir" $REQUIRES
fi
