#!/bin/ash -efu

. "${0%/*}"/mki-sh-functions

verbose "has started executing."

outname="${MKI_OUTNAME:-outname}"
outname="${outname##*/}"

imgsubdir="${MKI_IMAGESUBDIR:-}"
imgsubdir="${imgsubdir#/}"

compress=
case "${MKI_TAR_COMPRESS:-}" in
	lzma)                compress='--lzma' ;;
	bzip2|bz2|tarbz2|-j) compress='--bzip2' ;;
	gzip|gz|targz|-z)    compress='--gzip' ;;
esac

[ -d "$chroot" ] ||
	fatal "$dir: not look like a work directory of hasher."

mki-install tar

cat >"$chroot/tmp/packimage.sh"<<EOF
#!/bin/sh -efu
cd /.image/

[ -z "$imgsubdir" -o ! -d "./$imgsubdir" ] || cd "./$imgsubdir"

args=
[ ! -d .in ]       || args="\$args --exclude .in"
[ ! -d .host ]     || args="\$args --exclude .host"
[ ! -f .fakedata ] || args="\$args --exclude .fakedata"

exec tar --numeric-owner \$args $compress -cf '/.our/$outname' .
EOF

mki_exec_once "$chroot/tmp/packimage.sh"
mki-copy-our2out
