#!/bin/ash -efu

. "${0%/*}"/mki-sh-functions

verbose "has started executing."

type="${MKI_PACKTYPE:?pack type required}"

case "$type" in
	tarbz2)
		MKI_COMPRESSTYPE='bzip2'
		type='tar'
		;;
	boot|isoboot|isodata|squash|tar|data) ;;
	*) type='custom' ;;
esac
exec mki-pack-$type
