#!/bin/ash -efu
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2007-2012  Alexey Gladkov <gladkov.alexey@gmail.com>

ncpu=$(getconf _NPROCESSORS_ONLN 2>/dev/null) ||:

[ "$ncpu" != "0" ] ||
	ncpu=$(grep -c '^processor' /proc/cpuinfo 2>/dev/null) ||:

[ "$ncpu" != "0" ] ||
	ncpu=1

printf '%s\n' "$ncpu"
