#!/bin/ash -efu
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2007-2023  Alexey Gladkov <gladkov.alexey@gmail.com>

payload() {
	case "${cache_type:?must be defined in mki-cache}" in
		*-image-*)	scriptdir="${MKI_IMAGE_SCRIPTDIR:?Script directory required}" ;;
		*)		scriptdir="${MKI_SCRIPTDIR:?Script directory required}" ;;
	esac

	payload_makefile

	[ -d "$scriptdir" ] ||
		return 0

	find "$scriptdir" -type f -executable \
			\( \
				   \! -name '*~' \
				-a \! -name '*.bak' \
				-a \! -name '*.rpmnew' \
				-a \! -name '*.rpmsave' \
			\) \
			-execdir sha256sum '{}' '+' |
		cut -d\  -f1 |
		LANG=C sort
}
