#!/bin/ash -efu

. "${0%/*}"/mki-sh-functions
. "${0%/*}"/mki-sh-image-prepare

verbose "has started executing."

# Instrumental chroot should not have docs.
HSH_EXCLUDE_DOCS=1

run_mkaptbox() {
	rm -rf -- "$pkgbox/aptbox"
	env -i PATH="$PATH" \
	mkaptbox --without-stuff $verbose $quiet $target $apt_config $apt_prefix -- "$pkgbox"
}

if [ ! -d "$pkgbox/aptbox" ]; then
	run_mkaptbox
else
	env -i PATH="$PATH" "$pkgbox"/aptbox/apt-get update ||
		run_mkaptbox # Directory exists, but empty
fi

verbose "Work directory: $subdir."
[ -d "$chroot" ] ||
	hsh_initroot "$dir"

[ -z "$CHROOT_PACKAGES" ] ||
	mki-install $CHROOT_PACKAGES

ownership="$(stat -c '%u:%g' "$chroot/")" ||
	fatal "$chroot: unable to get ownership."

our="$chroot/.our"
verbose "Output directory for rooter user: $our."
mkdir $verbose -p -m1770 -- "$our"
chown $verbose "$ownership" -- "$our"

verbose "Subwork directory: $subdir."
mkdir $verbose -p -m1770 -- "$subdir"
chown $verbose "$ownership" -- "$subdir"

ln $verbose -nsf -- "$WORKDIRNAME" "$chroot/.image"
