#!/bin/ash -efu
#
# mki-cache-copy-subdirs
#
# This file is part of mkimage
# Copyright (C) 2007-2023  Alexey Gladkov <gladkov.alexey@gmail.com>
#
# This file is covered by the GNU General Public License,
# which should be included with mkimage as the file COPYING.
#

payload() {
	subdirs="${SUBDIRS:?subdirectories required}"

	curdir="${curdir:?mki-sh-functions not included}"
	workdirname="${workdirname:?mki-sh-functions not included}"
	outdirname="${outdirname:?mki-sh-functions not included}"

	payload_makefile

	local d
	for d in $subdirs; do
		payload_directory_state "$curdir/$d/$workdirname/$outdirname"
	done
}
