#!/bin/ash -efu
#
# mki-cache-run-scripts
#
# This file is part of mkimage
# Copyright (C) 2007-2023  Alexey Gladkov <gladkov.alexey@gmail.com>
#
# This file is covered by the GNU General Public License,
# which should be included with mkimage as the file COPYING.
#

case "${cache_type:?must be defined in mki-cache}" in
	*-image-*)	scriptdir="${MKI_IMAGE_SCRIPTDIR:?Script directory required}" ;;
	*)		scriptdir="${MKI_SCRIPTDIR:?Script directory required}" ;;
esac

payload() {
	makefile="${makefile:?mki-sh-functions not included}"

	stat --printf='%A\t%s\t%Y\n' "$makefile"

	[ -d "$scriptdir" ] ||
		return 0

	cd "$scriptdir" ||
		return 1

	find . -type f -executable \
			\( \
				   \! -name '*~' \
				-a \! -name '*.bak' \
				-a \! -name '*.rpmnew' \
				-a \! -name '*.rpmsave' \
			\) \
			-execdir sha256sum '{}' '+' |
		cut -d\  -f1 |
		sort
}
