#!/bin/sh -e
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2009  Alexey Gladkov <gladkov.alexey@gmail.com>

dir="$1"
topdir="$dir"

while [ -n "$topdir" ] && [ ! -d "$topdir/.mki" ]; do
	topdir="${topdir%/*}"
done
printf '%s\n' "${topdir:-$dir}"
