#!/bin/ash -efu

. "${0%/*}"/mki-sh-functions

verbose "has started executing."

case "$PROG" in
	*-run)
		exec env -i PATH="$PATH" \
		hsh-run --rooter $verbose $quiet ${HSH_NUMBER:+--number="$HSH_NUMBER"} "$dir" -- "$@"
		;;
	*-exec)
		exec env -i PATH="$PATH" \
		hsh-run --rooter $verbose $quiet ${HSH_NUMBER:+--number="$HSH_NUMBER"} "$dir" --execute="$1"
		;;
esac
