#!/bin/ash -efu

. shell-error

verbose="${VERBOSE:+-v}"
quiet="${QUIET:+-q}"
TARGET="${TARGET:+--target="$TARGET"}"
APT_CONFIG="${HSH_APT_CONFIG:+--apt-config="$HSH_APT_CONFIG"}"
APT_PREFIX="${HSH_APT_PREFIX:+--apt-prefix="$HSH_APT_PREFIX"}"

aptboxdir="${APTBOXDIR:?global aptbox required}"

exec env -i PATH="$PATH" \
	mkaptbox --without-stuff $verbose $quiet $TARGET $APT_CONFIG $APT_PREFIX -- $aptboxdir
