#!/bin/ash -efu

. "${0%/*}"/mki-sh-functions

verbose "has started executing."

[ -d "$chroot" ] ||
	fatal "$dir: not look like a work directory of hasher."

mki-install syslinux ||
	fatal "faild to install 'syslinux'."

[ -f "$chroot/.image/syslinux/isolinux.cfg" ] ||
	message 'Warning: /.image/syslinux/isolinux.cfg: not found.'

cat >"$chroot/tmp/packimage.sh"<<EOF
#!/bin/sh -efu
mkdir $verbose -p -- /.image/syslinux/alt0
cp $verbose -aLf /boot/vmlinuz /.image/syslinux/alt0/vmlinuz
cp $verbose -f /usr/lib/syslinux/isolinux.bin /.image/syslinux/
isolinux-config --base /syslinux /.image/syslinux/isolinux.bin
EOF

mki_exec_once "$chroot/tmp/packimage.sh"
