#!/bin/ash -efu

pkgboxdir="${PKGBOX:?directory required}"

pkgbox="$pkgboxdir/aptbox"

payload() {
	stat --printf='%A\t%s\t%Y\n' "$makefile"

	if [ -d "$pkgbox/var" ]; then
		cd "$pkgbox/var"
		find -name '*_release' -exec cat '{}' '+'
		cd - >/dev/null
	fi

	printf 'PACKAGES_EXPAND_METHOD=%s\n' "${PACKAGES_EXPAND_METHOD:-none}"

	local r
	for r in ${IMAGE_PACKAGES:-}; do
		if [ -f "$r" ]; then
			stat --printf='%A\t%s\t%Y\n' "$r"
		else
			printf '%s\n' "$r"
		fi
	done
}
