#!/bin/ash -efu

pkgboxdir="${PKGBOX:?directory required}"

pkgbox="$pkgboxdir/aptbox"

[ -d "$pkgbox" ] ||
	fatal "$pkgbox: not a directory."

payload() {
	stat --printf='%A\t%s\t%Y\n' "$makefile"

	cd "$pkgbox/var"
	find -name '*_release' -exec cat '{}' '+'
	cd - >/dev/null

	local requires="${MKI_REQUIRES:-}"

	[ -n "$requires" ] ||
		return 0

	local r
	for r in $requires; do
		if [ -f "$r" ]; then
			stat --printf='%A\t%s\t%Y\n' "$r"
		else
			printf '%s\n' "$r"
		fi
	done
}
