#!/bin/ash -efu
#
# mki-cache-copy-packages
#
# This file is part of mkimage
# Copyright (C) 2007-2023  Alexey Gladkov <gladkov.alexey@gmail.com>
#
# This file is covered by the GNU General Public License,
# which should be included with mkimage as the file COPYING.
#

payload() {
	pkgboxdir="${PKGBOX:?directory required}"
	pkgbox="$pkgboxdir/aptbox"

	payload_makefile
	payload_apt_list_release "$pkgbox/var"
	payload_image_packages
}
