#!/bin/ash -efu

. "${0%/*}"/mki-sh-functions

verbose "has started executing."

type="${MKI_PACKTYPE:?pack type required}"

outname="${MKI_OUTNAME:-outname}"
outname="${outname##*/}"

imgsubdir="${MKI_IMAGESUBDIR:-}"
imgsubdir="${imgsubdir#/}"

[ -d "$chroot" ] ||
	fatal "$dir: not look like a work directory of hasher."

if [ -x "$type" ]; then
	message "$type: executable file."

	install -m755 -- "$type" "$chroot/.host/script.sh"

	cat >"$chroot/.host/packimage.sh"<<-EOF
	#!/bin/sh -efu
	WORKDIR=/.image
	OUTNAME='/.our/$outname'
	SUBDIR='$imgsubdir'
	export WORKDIR OUTNAME SUBDIR
	/.host/script.sh
	EOF
else
	fatal "$type: unknown pack type."
fi

rc=0
mki-exec "$chroot/.host/packimage.sh" || rc=$?
rm -f -- "$chroot/.host/packimage.sh" "$chroot/.host/script.sh"
[ "$rc" -eq 0 ] ||
	exit $rc
mki-copy-our2out
