#!/bin/sh -efu
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2007-2023  Alexey Gladkov <gladkov.alexey@gmail.com>

payload() {
	pkgbox="${PKGBOX:?directory required}/aptbox"
	aptbox="${dir:?mki-sh-functions not included}/aptbox"

	payload_makefile
	payload_apt_list_release "$aptbox/var"
	payload_apt_list_release "$pkgbox/var"
}
