#!/bin/ash -efu

. "${0%/*}"/mki-sh-functions

verbose "has started executing."

[ -d "$chroot" ] ||
	fatal "$dir: not look like a work directory of hasher."

get_copy_args "$outdir/" "$chroot/.our/"

cd "$chroot/.our"
find -mindepth 1 -maxdepth 1 |
	xargs -r cp $cp_args -aft "$outdir" --

mki-run -- find /.our -mindepth 1 -maxdepth 1 -execdir rm -rf -- '{}' '+'
