#!/bin/sh -e
#
# mki-check-obsolete
#
# This file is part of mkimage
# Copyright (C) 2007-2009  Alexey Gladkov <gladkov.alexey@gmail.com>
#
# This file is covered by the GNU General Public License,
# which should be included with mkimage as the file COPYING.
#

. "${0%/*}"/mki-sh-functions

verbose "has started executing."

case "$1" in
	pack-image)
		[ -z "${MKI_OUTNAME:-}" -a -z "${MKI_PACKTYPE:-}" ] ||
			message 'WARNING: Variables MKI_OUTNAME and MKI_PACKTYPE are obsoletes. Use MKI_PACK_RESULTS instead.'
		;;
esac
