#!/bin/ash -efu
#
# mki-run-make
#
# This file is part of mkimage
# Copyright (C) 2007-2023  Alexey Gladkov <gladkov.alexey@gmail.com>
#
# This file is covered by the GNU General Public License,
# which should be included with mkimage as the file COPYING.
#

# shellcheck source=/bin/shell-quote
. shell-quote

include_without_workdir_check=1
# shellcheck source=tools/mki-sh-functions
. "${0%/*}"/mki-sh-functions

showenv() {
	local n v

	printenv |
		sed -ne 's/^\(GLOBAL_[^=]\+\)=/\1\t/p' |
	while read -r n v; do
		printf '%s="%s"\n' "$n" "$(quote_shell "$v")"
	done

	for n in MAKEFLAGS MAKELEVEL MFLAGS \
		PATH PWD SHELL TERM TMP TMPDIR USER;
	do
		v=
		eval v="\${$n:-}"

		[ -n "$v" ] || continue
		printf '%s="%s"\n' "$n" "$(quote_shell "$v")"
	done
}

dir="$1"; shift
if [ -z "$NO_REMOTES" ] && [ -z "${dir##*=*}" ]; then
	fatal 'remote build is no longer supported'
fi

cd "$dir"

# shellcheck disable=SC2046
eval exec env -i $(showenv) $(quote_shell "$@")
