#!/bin/ash -efu

data_tree="${COPY_TREE:?Data tree required}"

payload() {
	stat --printf='%A\t%s\t%Y\n' "$makefile"

	for d in $COPY_TREE; do
		d="$(readlink -ve "$d")"

		if [ -d "$d" ]; then
			cd "$d"
			find -mindepth 1 -printf '%M\t%s\t%T@\t%p\n'
		else
			cd "${d%/*}"
			stat --printf='%A\t%s\t%Y\t%n\n' "${d##*/}"
		fi
		cd - >/dev/null
	done
}
