#!/bin/ash -efu
# SPDX-License-Identifier: GPL-3.0
# Copyright (C) 2007-2023  Alexey Gladkov <gladkov.alexey@gmail.com>

workdir_check_status() {
	[ ! -d "${workdir_changed:?must be defined in mki-cache}" ]
}

workdir_change_status() {
	[ ! -d "${workdir_changed:?must be defined in mki-cache}" ] ||
		rmdir -- "$workdir_changed"
}

payload() {
	aptbox="${dir:?mki-sh-functions not included}/aptbox"
	curdir="${curdir:?mki-sh-functions not included}"
	workdirname="${workdirname:?mki-sh-functions not included}"
	outdirname="${outdirname:?mki-sh-functions not included}"

	printf '%s\n' "${MKI_OUTNAME:-}"

	payload_makefile
	payload_apt_list_release "$aptbox/var"
	payload_directory_state "$outdir"

	local d outdir
	for d in ${SUBDIRS:-}; do
		payload_directory_state "$d"
	done
}
