#!/bin/sh -e
#
# mki-check-obsolete
#
# This file is part of mkimage
# Copyright (C) 2007-2023  Alexey Gladkov <gladkov.alexey@gmail.com>
#
# This file is covered by the GNU General Public License,
# which should be included with mkimage as the file COPYING.
#

# shellcheck source=tools/mki-sh-functions
. "${0%/*}"/mki-sh-functions

verbose "has started executing."

case "$1" in
	pack-image)
		[ -z "${MKI_OUTNAME:-}" ] && [ -z "${MKI_PACKTYPE:-}" ] ||
			fatal 'ERROR: Variables MKI_OUTNAME and MKI_PACKTYPE are obsolete. Use MKI_PACK_RESULTS instead.'
		;;
	*)
		;;
esac
