#!/bin/ash -efu

aptbox="$dir/aptbox"

[ -d "$aptbox" ] ||
	fatal "$aptbox: not a directory."

payload() {
	stat --printf='%A\t%s\t%Y\n' "$makefile"

	cd "$aptbox/var"
	find -name '*_release' -exec cat '{}' '+'
	cd - >/dev/null

	local r
	for r in ${IMAGE_PACKAGES:-}; do
		if [ -f "$r" ]; then
			stat --printf='%A\t%s\t%Y\n' "$r"
		else
			printf '%s\n' "$r"
		fi
	done
}
