#!/bin/ash -efu

. "${0%/*}"/mki-sh-functions

nproc="${PACK_SQUASHFS_PROCESSORS:-}"
nproc="$(opt_check_number 'PACK_SQUASHFS_PROCESSORS' "$nproc")"

outname="${MKI_OUTNAME:-outname}"
outname="${outname##*/}"

[ -d "$chroot" ] ||
	fatal "$dir: not look like a work directory of hasher."

mki-install squashfsprogs

cat >"$chroot/tmp/packimage.sh"<<EOF
#!/bin/sh -efu

[ ! -e '/.our/$outname' ] ||
	rm -f -- '/.our/$outname'

mksquashfs /.image/ '/.our/$outname' ${nproc:+-processors $nproc} -e .in .host .fakedata
EOF

mki_exec_once "$chroot/tmp/packimage.sh"
mki-copy-our2out
