#!/bin/ash -efu
# SPDX-License-Identifier: GPL-3.0
# Copyright (C) 2023  Alexey Gladkov <gladkov.alexey@gmail.com>

payload() {
	patchesdir="${MKI_IMAGE_PATCHDIR:?Patches directory required}"

	payload_makefile

	[ -d "$patchesdir" ] ||
		return 0

	find "$patchesdir" -mindepth 1 -mindepth 1 \
			\( -type f -o -type l \) -a -name '*.patch' \
		-execdir sha256sum '{}' '+' |
		cut -d\  -f1 |
		sort
}
