#!/bin/sh -e
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2008-2009  Alexey Gladkov <gladkov.alexey@gmail.com>

for f in GNUmakefile makefile Makefile; do
	[ -s "$1/$f" ] ||
		continue
	printf '%s\n' "$1/$f"
	break
done
