#!/bin/ash -efu

. "${0%/*}"/mki-sh-functions

verbose "has started executing."

type="${MKI_PACKTYPE:?pack type required}"

outname="${MKI_OUTNAME:-outname}"
outname="${outname##*/}"

[ -d "$chroot" ] ||
	fatal "$dir: not look like a work directory of hasher."

update_chroot_fakedata

if [ -x "$type" ]; then
	message "$type: executable file."

	install -m755 -- "$type" "$chroot/tmp/script.sh"

	cat >"$chroot/tmp/packimage.sh"<<-EOF
	#!/bin/sh -efu
	WORKDIR=/.image
	OUTNAME='/.our/$outname'
	export WORKDIR OUTNAME
	/tmp/script.sh
	EOF
else
	fatal "$type: unknown pack type."
fi

mki_exec_once "$chroot/tmp/packimage.sh"

# XXXlegion: /tmp/script.sh will not be removed if /tmp/packimage.sh fail
rm -f -- "$chroot/tmp/script.sh"

mki-copy-our2out
