#!/bin/ash -efu
#
# mki-count-cpu
#
# This file is part of mkimage
# Copyright (C) 2007-2009  Alexey Gladkov <gladkov.alexey@gmail.com>
#
# This file is covered by the GNU General Public License,
# which should be included with mkimage as the file COPYING.
#

if [ -r '/proc/cpuinfo' ]; then
	grep '^processor' /proc/cpuinfo |wc -l
else
	echo '1'
fi
