#!/bin/sh -e
#
# mki-get-makefile
#
# This file is part of mkimage
# Copyright (C) 2008-2009  Alexey Gladkov <gladkov.alexey@gmail.com>
#
# This file is covered by the GNU General Public License,
# which should be included with mkimage as the file COPYING.
#

for f in GNUmakefile makefile Makefile; do
	[ -s "$1/$f" ] ||
		continue
	printf '%s\n' "$1/$f"
	break
done
