#!/bin/ash -efu

. "${0%/*}"/mki-sh-functions

verbose "has started executing."

hasher_args="--clean ${VERBOSE:+-v} ${QUIET:+-q} ${HSH_NUMBER:+--number="$HSH_NUMBER"}"

if [ -d "$subchroot" ]; then
	env -i PATH="$PATH" hsh $hasher_args "$subdir" ||
		fatal "$subdir: unable to clean workdir: rc=$?"
fi

if [ -d "$chroot" ]; then
	env -i PATH="$PATH" hsh $hasher_args "$dir" ||
		fatal "$dir: unable to clean workdir: rc=$?"
fi
