#!/bin/sh -efu
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2007-2023  Alexey Gladkov <gladkov.alexey@gmail.com>

# shellcheck source=tools/mki-sh-functions
. "${0%/*}"/mki-sh-functions

verbose "has started executing."

copy_functions() {
	[ -d "$chroot/.host" ] ||
		fatal "$chroot/.host directory does not exist"

	cp "${0%/*}"/mki-chroot-sh-functions "$chroot"/.host/mki-chroot-sh-functions
}

case "$PROG" in
	*-run)
		copy_functions
		exec env -i PATH="$PATH" ${HSH_NETWORK:+share_network=1} \
		hsh-run --rooter $verbose $quiet \
			${HSH_NUMBER:+--number="$HSH_NUMBER"} \
			${HSH_PROC:+--mountpoints=/proc} \
			"$dir" -- "$@"
		;;
	*-exec)
		copy_functions
		exec env -i PATH="$PATH" ${HSH_NETWORK:+share_network=1} \
		hsh-run --rooter $verbose $quiet \
			${HSH_NUMBER:+--number="$HSH_NUMBER"} \
			${HSH_PROC:+--mountpoints=/proc} \
			"$dir" --execute="$1"
		;;
	*)
		;;
esac
