#!/bin/ash -efu
# SPDX-License-Identifier: GPL-3.0
# Copyright (C) 2007-2023  Alexey Gladkov <gladkov.alexey@gmail.com>

payload() {
	payload_makefile

	local d dir
	for dir in ${COPY_TREE:-}; do
		d="$(readlink -ve "$dir")" ||
			fatal "$dir: not available."

		if [ -d "$d" ]; then
			payload_directory_state "$d"
		else
			payload_file_state "${d%/*}" "${d##*/}"
		fi
	done
}
