#!/bin/ash -efu

subdirs="${SUBDIRS:?subdirectories required}"

payload() {
	local d

	stat --printf='%A\t%s\t%Y\n' "$makefile"

	for d in $subdirs; do
		[ -d "$curdir/$d/$workdirname/$outdirname" ] ||
			continue

		cd "$curdir/$d/$workdirname/$outdirname"
		find -mindepth 1 -printf '%M\t%s\t%T@\t%p\n'
		cd - >/dev/null
	done
}
