#!/bin/ash -efu
#
# mki-cache-build-image
#
# This file is part of mkimage
# Copyright (C) 2007-2023  Alexey Gladkov <gladkov.alexey@gmail.com>
#
# This file is covered by the GNU General Public License,
# which should be included with mkimage as the file COPYING.
#

payload() {
	aptbox="${dir:?mki-sh-functions not included}/aptbox"
	makefile="${makefile:?mki-sh-functions not included}"

	stat --printf='%A\t%s\t%Y\n' "$makefile"

	payload_apt_list_release "$aptbox/var"
	payload_image_packages
}
