#!/bin/ash -efu

. "${0%/*}"/mki-sh-functions

verbose "has started executing."

outname="${MKI_OUTNAME:-outname}"
outname="${outname##*/}"

imgsubdir="${MKI_IMAGESUBDIR:-}"
imgsubdir="${imgsubdir#/}"

[ -d "$chroot" ] ||
	fatal "$dir: not look like a work directory of hasher."

mki-install mkisofs

cat >"$chroot/.host/packimage.sh"<<EOF
#!/bin/sh -efu
cd /tmp
cat > .mkisofsrc <<-__EOF__
	APPI="${ISODATA_APPI:-}"
	COPY="${ISODATA_COPY:-}"
	ABST="${ISODATA_ABST:-}"
	BIBL="${ISODATA_BIBL:-}"
	PREP="${ISODATA_PREP:-}"
	PUBL="${ISODATA_PUBL:-}"
	SYSI="${ISODATA_SYSI:-}"
	VOLI="${ISODATA_VOLI:-}"
	VOLS="${ISODATA_VOLS:-}"
__EOF__

imgdir=/.image
[ -z "$imgsubdir" -o ! -d "/.image/$imgsubdir" ] ||
	imgdir="/.image/$imgsubdir"
		
rc=0
mkisofs $verbose -T -J -l -r -U -o '/.our/$outname' "\$imgdir/" || rc=\$?

rm -f -- .mkisofsrc
exit \$rc
EOF

mki_exec_once "$chroot/.host/packimage.sh"
mki-copy-our2out
